### ISSUE TITLE
Barcodes are deleted incorrectly

### ISSUE THREAD

**Issue by Vincentwang987** [AndrewPerson/Lit-Paragon-Client#118]
Step 1. Load new barcodes
Step 2. Rename a barcode
Step 3. Delete the newly named barcode
Step 4. Wonder why this can happen

Reloading it fixes the issue however, it may cause some confusion

https://user-images.githubusercontent.com/93361820/167231262-befdc5b9-99fa-4b96-903e-465809c22b5e.mp4

**Comment by AndrewPerson** [comment]
Okay. Now this should be _definitely_ fixed!
