### ISSUE TITLE
Full screen barcodes shouldn't deselect when moving the points [Extension]

### ISSUE THREAD

**Issue by Vincentwang987** [AndrewPerson/Lit-Paragon-Client#125]
1. Go to the barcodes extension
2. Click the "Show" button
3. Move the button's points

https://user-images.githubusercontent.com/93361820/168456970-fca98fe8-1ade-4fb6-8373-4cec2093de9f.mp4

**Comment by AndrewPerson** [comment]
Sorry for the late response, but that problem should be fixed now!
