### ISSUE TITLE
SUGGESTION: add full name of casual teacher not the first 3 letters

### ISSUE THREAD

**Issue by unseeyou** [AndrewPerson/Lit-Paragon-Client#166]
it's just less confusing and the main teachers don't have their names shortened

P.S. how do I add a label

**Comment by AndrewPerson** [comment]
Paragon tries to display the full name for substitute teacher, but falls back to their "code" when that isn't available, which is just 4 letters of their name. Unfortunately, most substitute teachers don't have their name provided, so Paragon has to use their codes. I'm not entirely sure what you mean by a label, so feel free to reopen this if you want to clarify that.

**Comment by unseeyou** [comment]
SCHOOL API FIXED THIS YAY
