### ISSUE TITLE
[BUG/IMPROVEMENT] support special characters in names such as " ' "

### ISSUE THREAD

**Issue by unseeyou** [AndrewPerson/Lit-Paragon-Client#179]
No context I just got confused by having Geography with A Dad even though it is D'ad

**Comment by unseeyou** [comment]
![image](https://github.com/AndrewPerson/Lit-Paragon-Client/assets/84846449/e5e4a9f0-629d-4f1b-be07-45bb135c186f)

**Comment by AndrewPerson** [comment]
Unfortunately, the school API doesn't have the special characters in the first place, so there isn't a difference between A Dad. and A. D'ad. If it does start including them, they should appear on Paragon.
